services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./install_phi3.sh:/install_phi3.sh
    expose:
      - 11434
    ports:
      - "11434:11434"
    entrypoint: ["/usr/bin/bash", "/install_phi3.sh"]
  
  streamlit_app:
    image: python:3.10
    container_name: streamlit_app
    volumes:
      - ./src/:/app/
      - ./.env:/.env
      - ./setup_python.sh:/setup_python.sh
      - ./dist/:/dist
    ports:
      - "8501:8501" 
    depends_on:
      - elasticsearch
      - ollama
    entrypoint: ["/usr/bin/bash", "/setup_python.sh"]

volumes:
  ollama: