services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./install_phi3.sh:/install_phi3.sh

    ports:
      - "11434:11434"
    entrypoint: ["/usr/bin/bash", "/install_phi3.sh"]

volumes:
  ollama: