{
 "title": "YT Summaries for Cooking",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  question,\r\n  answer\r\n  FROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY timestamp DESC\r\nLIMIT 5\r\n"
    }
   ]
  },
  {
   "title": "+1/-1",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\r\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\r\nFROM feedback\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\n"
    }
   ]
  },
  {
   "title": "TS - Response time per Model",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  avg(response_time),\r\n  model_used\r\nFROM conversations\r\ngroup by model_used, timestamp\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "TS - Tokens per Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  sum(total_tokens),\n  model_used\nFROM conversations\ngroup by model_used, timestamp\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OpenAI cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  openai_cost\r\nFROM conversations\r\nWHERE openai_cost > 0\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Model used",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  model_used,\r\n  COUNT(*) as count\r\nFROM conversations\r\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY model_used\r\n"
    }
   ]
  }
 ]
}